# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef33fe2c2a4213784e7947604f93988928240cb7d2570ab55b4263e456fa068dc86f86ed3460a437ebb7e27163698271634b19dbd63bfa4cfa65b18549728286

test:
  secret_key_base: 94c3c224b594489203bff1ce5ada391c0dae726a2ba804d4c6a78a419ad3f7ad43ab0c2a66638ba85ad7a2bf442f71513997787fc336900fbd3ac9999e5e230f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
